[pytest]
testpaths =
    src/tests
python_files =
    test_*.py
filterwarnings =
    ignore::Warning:matplotlib.*
    ignore::pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:.*urllib3 v2 only supports OpenSSL.*:urllib3.exceptions.NotOpenSSLWarning