import argparse
import json
from pathlib import Path
from datetime import datetime


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}


def count_images(folder: Path):
    if not folder.exists():
        return 0

    return sum(
        1 for p in folder.rglob("*")
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )


def data_qa_agent(data_dir: Path):
    report = {
        "agent": "Data QA Agent",
        "data_dir": str(data_dir),
        "exists": data_dir.exists(),
        "splits": {},
        "warnings": [],
    }

    for split in ["train", "val", "test"]:
        split_dir = data_dir / split

        normal_count = count_images(split_dir / "NORMAL")
        pneumonia_count = count_images(split_dir / "PNEUMONIA")

        report["splits"][split] = {
            "NORMAL": normal_count,
            "PNEUMONIA": pneumonia_count,
            "total": normal_count + pneumonia_count,
        }

        if normal_count == 0 or pneumonia_count == 0:
            report["warnings"].append(
                f"{split} split has missing or empty class folders."
            )

    return report


def evaluation_agent(metrics_path: Path):
    report = {
        "agent": "Evaluation Agent",
        "metrics_path": str(metrics_path),
        "exists": metrics_path.exists(),
        "metrics": {},
        "warnings": [],
    }

    if not metrics_path.exists():
        report["warnings"].append("Metrics file not found.")
        return report

    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    report["metrics"] = metrics

    if metrics.get("pr_auc", 0) < 0:
        report["warnings"].append("PR-AUC is negative, which usually indicates a calculation error.")

    if metrics.get("brier", 1) > 0.25:
        report["warnings"].append("Brier score is relatively high; calibration may need inspection.")

    return report


def explainability_agent(figures_dir: Path):
    expected_figures = [
        "roc_test.png",
        "pr_test.png",
        "confusion_matrix.png",
        "gradcam_true_positive.png",
        "gradcam_true_negative.png",
        "gradcam_false_positive.png",
        "gradcam_false_negative.png",
    ]

    existing = []
    missing = []

    for name in expected_figures:
        path = figures_dir / name
        if path.exists():
            existing.append(name)
        else:
            missing.append(name)

    return {
        "agent": "Explainability Agent",
        "figures_dir": str(figures_dir),
        "existing_figures": existing,
        "missing_figures": missing,
        "warnings": [
            f"Missing figure: {name}" for name in missing
        ],
    }


def model_card_agent(model_card_path: Path):
    required_sections = [
        "Model Summary",
        "Intended Use",
        "Not Intended For",
        "Dataset",
        "Evaluation",
        "Limitations",
        "Ethical Considerations",
    ]

    report = {
        "agent": "Model Card Agent",
        "model_card_path": str(model_card_path),
        "exists": model_card_path.exists(),
        "missing_sections": [],
        "warnings": [],
    }

    if not model_card_path.exists():
        report["warnings"].append("MODEL_CARD.md not found.")
        return report

    text = model_card_path.read_text(encoding="utf-8")

    for section in required_sections:
        if section not in text:
            report["missing_sections"].append(section)
            report["warnings"].append(f"Missing model card section: {section}")

    return report


def write_markdown_report(reports, output_path: Path):
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("# Multi-Agent ML Audit Report")
    lines.append("")
    lines.append(f"Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append("")
    lines.append("This report is generated by a lightweight multi-agent audit workflow.")
    lines.append("The agents do not make clinical decisions. They check engineering, evaluation, documentation, and explainability artifacts.")
    lines.append("")

    for report in reports:
        lines.append(f"## {report['agent']}")
        lines.append("")

        warnings = report.get("warnings", [])

        if warnings:
            lines.append("### Warnings")
            for warning in warnings:
                lines.append(f"- {warning}")
            lines.append("")
        else:
            lines.append("No warnings detected.")
            lines.append("")

        lines.append("### Details")
        lines.append("```json")
        lines.append(json.dumps(report, indent=2))
        lines.append("```")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved audit report to {output_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default="data/chest_xray")
    parser.add_argument("--metrics", default="outputs/metrics/test_metrics.json")
    parser.add_argument("--figures-dir", default="outputs/figures")
    parser.add_argument("--model-card", default="MODEL_CARD.md")
    parser.add_argument("--out", default="outputs/reports/ml_audit_report.md")

    args = parser.parse_args()

    reports = [
        data_qa_agent(Path(args.data_dir)),
        evaluation_agent(Path(args.metrics)),
        explainability_agent(Path(args.figures_dir)),
        model_card_agent(Path(args.model_card)),
    ]

    write_markdown_report(reports, Path(args.out))


if __name__ == "__main__":
    main()